msm8960: fix unused-parameter errors when no extensions are defined
If no extensions are defined these errors are generated:

hardware/qcom/audio-caf/msm8960/hal/audio_extn/audio_extn.c:384:53:
error: unused parameter 'adev' [-Werror,-Wunused-parameter]
void audio_extn_set_parameters(struct audio_device *adev,
                                                    ^
hardware/qcom/audio-caf/msm8960/hal/audio_extn/audio_extn.c:385:50:
error: unused parameter 'parms' [-Werror,-Wunused-parameter]
                               struct str_parms *parms)
                                                 ^
hardware/qcom/audio-caf/msm8960/hal/audio_extn/audio_extn.c:396:59:
error: unused parameter 'adev' [-Werror,-Wunused-parameter]
void audio_extn_get_parameters(const struct audio_device *adev,
                                                          ^
hardware/qcom/audio-caf/msm8960/hal/audio_extn/audio_extn.c:397:49:
error: unused parameter 'query' [-Werror,-Wunused-parameter]
                              struct str_parms *query,
                                                ^

Change-Id: Ief26a51adfd9700094d8e79f04ecc8cd51a774f6