Revert "Revert "audio: Use project pathmap""
This reverts commit 014c03aa6bb787f17b03abe7a2f9c789f9a768f9.

Revert this commit as for some devices the audio path id different.
Example: building ArrowOS 11.0 for marlin(MSM8996) gives the following error:

hardware/qcom/audio/default/post_proc/volume_listener.c:29:10: fatal error: 'platform_api.h' file not found #include <platform_api.h>

as it uses hardware/qcom/audio/default/ instead of hardware/qcom/audio/

Change-Id: If22270772e1a33872a9d3c8bf7fba5b151fe790d